# Generated by Django 5.0 on 2024-01-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0002_alter_manga_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='img',
            field=models.ImageField(upload_to='media/img/'),
        ),
    ]
