# Generated by Django 5.0 on 2024-01-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capitulos', '0002_alter_capitulos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='video',
            field=models.FileField(upload_to='videos/%y'),
        ),
    ]
